import { describe, expect, it } from 'vitest'
import {
  MAX_HARVEST_DEPTH,
  NEVER_CONTENT_TAGS,
  asReaderDocument,
  asReaderElement
} from '@shared/reader/wire.js'
import { isIgnorable } from '@shared/reader/structure.js'
import { el } from './reader-fixtures.js'

/**
 * The boundary between the page and the extractor.
 *
 * Everything the parser refuses is a case of **the page having tampered with the answer**, not of a
 * version skew: the transcription script is generated by this same build, but it runs in the page's
 * main world where the page's own code can replace its result. So the parser is strict where
 * `filters/picker-wire.ts` is forgiving, and each of the tests below is one way a page could try to
 * hand the core a shape the extractor was not written for.
 */

/** A minimal well-formed document, as an object the parser has not seen typed. */
function raw(overrides: Readonly<Record<string, unknown>> = {}): Record<string, unknown> {
  return {
    root: { kind: 'element', tag: 'body', id: '', classes: [], attributes: {}, children: [] },
    meta: { 'og:title': 'A title' },
    documentTitle: 'A title',
    lang: 'en',
    url: 'https://example.test/',
    ...overrides
  }
}

describe('reading what the page sent back', () => {
  it('accepts a well-formed document', () => {
    const parsed = asReaderDocument(raw())
    expect(parsed?.root.tag).toBe('body')
    expect(parsed?.meta['og:title']).toBe('A title')
    expect(parsed?.url).toBe('https://example.test/')
    expect(parsed?.truncated).toBe(false)
  })

  it('carries the truncation flag through, because everything downstream depends on it', () => {
    expect(asReaderDocument(raw({ truncated: true }))?.truncated).toBe(true)
    // Anything other than `true` is not truncation: a page setting it to a string must not be able to
    // make the core refuse a page it would otherwise have read.
    expect(asReaderDocument(raw({ truncated: 'yes' }))?.truncated).toBe(false)
  })

  it('lower-cases tag names so nothing downstream has to', () => {
    const parsed = asReaderElement({
      kind: 'element',
      tag: 'DIV',
      id: '',
      classes: [],
      attributes: {},
      children: []
    })
    expect(parsed?.tag).toBe('div')
  })

  it('keeps the hidden marker and nothing else truthy', () => {
    const base = { kind: 'element', tag: 'div', id: '', classes: [], attributes: {}, children: [] }
    expect(asReaderElement({ ...base, hidden: true })?.hidden).toBe(true)
    expect(asReaderElement({ ...base, hidden: 'yes' })?.hidden).toBeUndefined()
  })

  it('reads a text node', () => {
    const parsed = asReaderElement({
      kind: 'element',
      tag: 'p',
      id: '',
      classes: [],
      attributes: {},
      children: [{ kind: 'text', text: 'hello' }]
    })
    expect(parsed?.children).toEqual([{ kind: 'text', text: 'hello' }])
  })

  it('refuses every shape that is not the one this build produces', () => {
    const node = (overrides: Readonly<Record<string, unknown>>): Record<string, unknown> => ({
      kind: 'element',
      tag: 'div',
      id: '',
      classes: [],
      attributes: {},
      children: [],
      ...overrides
    })
    const refused: readonly [string, unknown][] = [
      ['not an object', 'body'],
      ['null', null],
      ['an array', []],
      ['an unknown kind', { kind: 'comment' }],
      ['a text node with no text', { kind: 'text' }],
      ['a text node whose text is a number', { kind: 'text', text: 7 }],
      ['an element with no tag', node({ tag: undefined })],
      ['an element with an empty tag', node({ tag: '' })],
      ['an element whose id is not a string', node({ id: 7 })],
      ['classes that are not an array', node({ classes: 'a b' })],
      ['a class that is not a string', node({ classes: ['a', 7] })],
      ['attributes that are an array', node({ attributes: [] })],
      ['an attribute value that is not a string', node({ attributes: { href: 7 } })],
      ['children that are not an array', node({ children: {} })],
      ['one malformed child among good ones', node({ children: [{ kind: 'text', text: 'a' }, 7] })]
    ]
    for (const [name, value] of refused) {
      expect(asReaderElement(value), name).toBeNull()
    }
  })

  it('refuses a document with any field missing or of the wrong type', () => {
    const refused: readonly [string, unknown][] = [
      ['not an object', 'a document'],
      ['null', null],
      ['no root', raw({ root: undefined })],
      ['a malformed root', raw({ root: { kind: 'text', text: 'x' } })],
      ['meta that is not a record', raw({ meta: [] })],
      ['a meta value that is not a string', raw({ meta: { a: 7 } })],
      ['a title that is not a string', raw({ documentTitle: 7 })],
      ['a lang that is not a string', raw({ lang: null })],
      ['a url that is not a string', raw({ url: undefined })]
    ]
    for (const [name, value] of refused) {
      expect(asReaderDocument(value), name).toBeNull()
    }
  })

  it('refuses a tree deeper than the walk will go rather than trimming it', () => {
    // Trimming would be a silent cut, and a silently cut tree is exactly the input on which the
    // extractor's measurements are a measurement of something else.
    const deep = (depth: number): Record<string, unknown> => ({
      kind: 'element',
      tag: 'div',
      id: '',
      classes: [],
      attributes: {},
      children: depth === 0 ? [] : [deep(depth - 1)]
    })
    expect(asReaderElement(deep(MAX_HARVEST_DEPTH - 1))).not.toBeNull()
    expect(asReaderElement(deep(MAX_HARVEST_DEPTH + 1))).toBeNull()
  })
})

describe('the skip list the page applies and the drop list the extractor applies', () => {
  it('is one list, so the page cannot remove something the extractor would have kept', () => {
    // A transcription that skipped *more* than the extractor drops would take content out with no way
    // for either side to notice. Sharing the constant makes the containment true by construction; this
    // test holds the constant to being the thing `isIgnorable` consults.
    for (const tag of NEVER_CONTENT_TAGS) {
      expect(isIgnorable(el(tag)), tag).toBe(true)
    }
    expect(isIgnorable(el('p'))).toBe(false)
  })
})
