/**
 * The page, as reader mode is allowed to see it.
 *
 * ## Why the extractor never touches a DOM
 *
 * The article extraction is the interesting half of reader mode and it is almost entirely
 * judgement: which container is the article, what inside it is furniture, whether the page is an
 * article at all. Judgement that can only be exercised against a live `Element` is judgement no
 * test can pin down, so the same split `filters/picker-wire.ts` made is made again here — the page
 * is transcribed into plain data at the boundary, and everything after that is a pure function over
 * that data.
 *
 * ## Why a real `Element` cannot satisfy this shape, unlike `PickerElement`
 *
 * `PickerElement` is satisfied structurally by a real `Element` because the picker only ever needs
 * an element's *name*: tag, id, classes, attributes, position. Reader mode needs its **text**, and
 * text is not in `Element.children` — it is in `childNodes`, interleaved with the elements. There is
 * no way to describe "the children of this element, in order, including the text" in terms an
 * `Element` already answers, so this is a wire shape rather than a structural subset, and the walk
 * that produces it runs in the page (see `main/reader/harvest.ts`).
 *
 * That is also why the shape distinguishes text nodes explicitly rather than folding a `textContent`
 * onto each element: `<p>Read <a href="…">the notice</a> first.</p>` has to survive with its inline
 * order intact, and an element that carried only its concatenated text would render as
 * "Readthe noticefirst."
 *
 * ## Why the parser is strict rather than forgiving
 *
 * `picker-wire.ts` parses loosely on the grounds that an older build may answer anything. Nothing
 * here has that excuse — the transcription script is generated by this same build — but it has a
 * worse problem instead: the script runs in the page's *main* world, so the page's own code can
 * replace the result before it comes back. Anything off-shape is therefore tampering rather than
 * skew, and the honest response to tampering is to refuse the whole document rather than to repair
 * part of it. `asReaderDocument` rebuilds the tree from scratch and returns `null` at the first
 * thing it does not recognise, which is what makes every function downstream total over a shape it
 * can rely on.
 *
 * Zod-free and dependency-free: the reader page imports these types, and a validation library in
 * that bundle is half a megabyte of parse work on every window open (see `ARCHITECTURE.md`).
 */

/** One run of text, exactly as the page had it — whitespace included, normalised later. */
export interface ReaderTextNode {
  readonly kind: 'text'
  readonly text: string
}

export interface ReaderElementNode {
  readonly kind: 'element'
  /** Lower-cased tag name. */
  readonly tag: string
  readonly id: string
  readonly classes: readonly string[]
  /** Only the names in `CARRIED_ATTRIBUTES`; everything else is dropped at the boundary. */
  readonly attributes: Readonly<Record<string, string>>
  readonly children: readonly ReaderNode[]
  /**
   * The page was not showing this element.
   *
   * Set from `Element.checkVisibility()` in the page, which is the only place the answer exists —
   * and the reason this is a flag rather than an omission is that it is *the* answer to "drop
   * anything the blocker would have hidden". A cosmetic filter rule hides by injecting
   * `display: none !important`, so an element the blocker removed and an element the site itself
   * collapsed are indistinguishable here, which is correct: reader mode should show what the page
   * showed, not what its markup claims.
   *
   * A hidden element arrives as a childless leaf, so a collapsed mega-menu costs one node rather
   * than four hundred. The *decision* to drop it still lives in `content.ts` where a test can reach
   * it, which is the whole point of not making it an omission.
   */
  readonly hidden?: boolean | undefined
}

export type ReaderNode = ReaderTextNode | ReaderElementNode

export interface ReaderDocument {
  /** The `<body>` of the harvested page. */
  readonly root: ReaderElementNode
  /**
   * `<meta>` in the head, keyed by lower-cased `name` or `property`.
   *
   * A flat record rather than nodes in the tree, because head metadata is looked up by name and
   * never walked — and because `og:title` and `article:published_time` are the two places a page
   * states its own headline and date without a heuristic being involved.
   */
  readonly meta: Readonly<Record<string, string>>
  /** `document.title`, verbatim. Often the headline plus the site name; see `metadata.ts`. */
  readonly documentTitle: string
  /** `<html lang>`, or empty. */
  readonly lang: string
  /** The address harvested, for the link back to the original. */
  readonly url: string
  /**
   * The walk stopped early: the page has more nodes than `HARVEST_NODE_BUDGET`, or nests deeper
   * than `MAX_HARVEST_DEPTH`.
   *
   * A separate flag rather than a silent cut, because a partial document is exactly the input on
   * which a confident-looking extraction is a lie. `extractArticle` refuses outright when this is
   * set — see `REFUSAL_REASONS`.
   */
  readonly truncated: boolean
}

/**
 * Tags whose contents are never article text, dropped at the boundary and again in the walk.
 *
 * One constant used in both places on purpose. The transcription needs a skip list for size — a
 * single `<script>` holding a serialised application state is larger than the article — and a skip
 * list that were *wider* than the extractor's own drop list would silently remove content the
 * extractor would have kept, with no way to notice from either side. Sharing the constant makes the
 * containment true by construction instead of true by review.
 *
 * `meta` is deliberately absent: it carries no text, so it costs nothing, and schema.org markup
 * states a publication date as `<meta itemprop="datePublished">` *inside* the body, which
 * `metadata.ts` reads.
 */
export const NEVER_CONTENT_TAGS: ReadonlySet<string> = new Set([
  'script',
  'style',
  'noscript',
  'template',
  'link',
  'base',
  'iframe',
  'frame',
  'frameset',
  'object',
  'embed',
  'applet',
  'param',
  'canvas',
  'svg',
  'math',
  'video',
  'audio',
  'source',
  'track',
  'map',
  'area',
  'form',
  'input',
  'textarea',
  'select',
  'option',
  'optgroup',
  'button',
  'fieldset',
  'legend',
  'label',
  'dialog',
  'progress',
  'meter',
  'output'
])

/**
 * Attributes carried across the boundary.
 *
 * An allowlist, and a short one, because the transcription crosses a process boundary in one
 * message: a framework-heavy page carries dozens of `data-` attributes per element holding
 * serialised state, none of which says anything about whether an element is an article.
 *
 * `href` and `src` are read from the DOM *property* rather than the attribute, so they arrive
 * already absolute — which is why nothing downstream resolves a relative URL, and why nothing
 * downstream needs to know the page's base address to do it.
 */
export const CARRIED_ATTRIBUTES: readonly string[] = [
  'href',
  'src',
  'alt',
  'datetime',
  'role',
  'itemprop',
  'rel',
  'lang',
  'aria-hidden',
  'aria-label',
  'content'
]

/**
 * How many nodes the transcription may emit before it gives up.
 *
 * An article page is two to six thousand nodes; a heavy single-page application is twenty to
 * thirty thousand. Sixty thousand is above anything that is still a document and below the point
 * where the message itself becomes the problem. Exceeding it sets `truncated`, and a truncated
 * document is refused rather than extracted — the budget exists to bound the work, not to quietly
 * halve an article.
 */
export const HARVEST_NODE_BUDGET = 60_000

/**
 * How deep the transcription may descend.
 *
 * Real documents nest around forty deep; three hundred is far past every layout wrapper and still
 * shallow enough that the recursive walks over this tree cannot exhaust the stack. Like the node
 * budget, hitting it sets `truncated` rather than trimming a branch away.
 */
export const MAX_HARVEST_DEPTH = 300

function asStringArray(value: unknown): readonly string[] | null {
  if (!Array.isArray(value)) return null
  const items: string[] = []
  for (const item of value as readonly unknown[]) {
    if (typeof item !== 'string') return null
    items.push(item)
  }
  return items
}

function asStringRecord(value: unknown): Readonly<Record<string, string>> | null {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return null
  const record: Record<string, string> = {}
  for (const [key, item] of Object.entries(value)) {
    if (typeof item !== 'string') return null
    record[key] = item
  }
  return record
}

function asUnknownArray(value: unknown): readonly unknown[] | null {
  return Array.isArray(value) ? (value as readonly unknown[]) : null
}

function fieldsOf(value: unknown): Readonly<Record<string, unknown>> | null {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return null
  return value as Readonly<Record<string, unknown>>
}

function asNode(value: unknown, depth: number): ReaderNode | null {
  if (depth > MAX_HARVEST_DEPTH) return null
  const raw = fieldsOf(value)
  if (raw === null) return null

  if (raw['kind'] === 'text') {
    const text = raw['text']
    return typeof text === 'string' ? { kind: 'text', text } : null
  }
  if (raw['kind'] !== 'element') return null

  const tag = raw['tag']
  const id = raw['id']
  const classes = asStringArray(raw['classes'])
  const attributes = asStringRecord(raw['attributes'])
  const rawChildren = asUnknownArray(raw['children'])
  if (typeof tag !== 'string' || tag === '') return null
  if (typeof id !== 'string') return null
  if (classes === null || attributes === null || rawChildren === null) return null

  const children: ReaderNode[] = []
  for (const rawChild of rawChildren) {
    const child = asNode(rawChild, depth + 1)
    // One unrecognised child fails the whole document rather than being skipped. A skipped child is
    // a hole in the article that nothing reports; see the docblock on tampering.
    if (child === null) return null
    children.push(child)
  }

  return {
    kind: 'element',
    tag: tag.toLowerCase(),
    id,
    classes,
    attributes,
    children,
    ...(raw['hidden'] === true ? { hidden: true } : {})
  }
}

/** An element node, or `null` when the value is anything else. */
export function asReaderElement(value: unknown): ReaderElementNode | null {
  const node = asNode(value, 0)
  return node !== null && node.kind === 'element' ? node : null
}

/**
 * What came back from the page, rebuilt or refused.
 *
 * Total, and strict: see the docblock. `null` becomes the `unreadable` refusal, which is a state
 * the reader page words for the user rather than an exception somebody has to catch.
 */
export function asReaderDocument(value: unknown): ReaderDocument | null {
  const raw = fieldsOf(value)
  if (raw === null) return null

  const root = asReaderElement(raw['root'])
  const meta = asStringRecord(raw['meta'])
  const documentTitle = raw['documentTitle']
  const lang = raw['lang']
  const url = raw['url']
  if (root === null || meta === null) return null
  if (typeof documentTitle !== 'string' || typeof lang !== 'string' || typeof url !== 'string') {
    return null
  }

  return { root, meta, documentTitle, lang, url, truncated: raw['truncated'] === true }
}
